version: "3.7"
services:
    webapp:
        build:
            context: ./DockerWebApp
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        networks:
            - my-network
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MyPassword001"
            ACCEPT_EULA: "Y"
        ports:
        - "1433:1433"
networks:
    my-network:
        external: true