version: "3.7"
services:
    webapp:
        build:
            context: ./DockerWebApp
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - my-network
networks:
    my-network:
        external: true