version: "3.7"
services:
    webapp:
        build:
            context: ./DockerWebApp
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
            - ASPNETCORE_ENVIRONMENT=Production
        networks:
            - my-network
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MyPassword001"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - my-network
        volumes:
            - backups:/var/opt/mssql/backups
            - datafiles:/var/opt/sqlserver
            - system:/var/opt/mssql
volumes:
    backups:
    datafiles:
    system:
networks:
    my-network:
        